name: Build and deploy

on:
  push:
    branches-ignore: "**"
    tags:
      - "[0-9]+(.[0-9]+(-beta)?)*"

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build and deploy (python)
        run: |
          python3 -m pip install --user virtualenv
          python3 -m virtualenv fec
          source fec/bin/activate
          pip install -r requirements.txt
          pip install twine
          python setup.py install test sdist bdist_wheel
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.NEWS_ENG_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.NEWS_ENG_PYPI_PASSWORD }}
